version: '3.3'
services:
  nginx:
    image: nginx:latest
    container_name: "nginx"
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "80:80"
      - "443:443"
    restart: always
    working_dir: /var/www
    volumes:
      - ./../:/var/www
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
      - /etc/hosts:/etc/hosts:ro
    depends_on:
      - fpm-56
      - fpm-70
      - fpm-71
      - fpm-72
      - fpm-73
      - fpm-74
    networks:
      default:

  fpm-56:
    image: silvanei/php:5.6-fpm
    container_name: "5.6-fpm"
    env_file:
      - .env
    restart: always
    working_dir: /var/www
    volumes:
      - ./../:/var/www
      - /tmp:/tmp
      - /etc/hosts:/etc/hosts:ro
    networks:
      default:

  fpm-70:
    image: silvanei/php:7.0-fpm
    container_name: "7.0-fpm"
    env_file:
      - .env
    restart: always
    working_dir: /var/www
    volumes:
      - ./../:/var/www
      - /tmp:/tmp
      - /etc/hosts:/etc/hosts:ro
    networks:
      default:

  fpm-71:
    image: silvanei/php:7.1-fpm
    container_name: "7.1-fpm"
    env_file:
      - .env
    restart: always
    working_dir: /var/www
    volumes:
      - ./../:/var/www
      - /tmp:/tmp
      - /etc/hosts:/etc/hosts:ro
    networks:
      default:

  fpm-72:
    image: silvanei/php:7.2-fpm
    container_name: "7.2-fpm"
    env_file:
      - .env
    restart: always
    working_dir: /var/www
    volumes:
      - ./../:/var/www
      - /tmp:/tmp
      - /etc/hosts:/etc/hosts:ro
    networks:
      default:

  fpm-73:
    image: silvanei/php:7.3-fpm
    container_name: "7.3-fpm"
    env_file:
      - .env
    restart: always
    working_dir: /var/www
    volumes:
      - ./../:/var/www
      - /tmp:/tmp
      - /etc/hosts:/etc/hosts:ro
    networks:
      default:

  fpm-74:
    image: silvanei/php:7.4-fpm
    container_name: "7.4-fpm"
    env_file:
      - .env
    restart: always
    working_dir: /var/www
    volumes:
      - ./../:/var/www
      - /tmp:/tmp
      - /etc/hosts:/etc/hosts:ro
    networks:
      default:

  blackfire:
    image: blackfire/blackfire
    restart: always
    container_name: blackfire
    env_file:
      - .env
  mysql.docker.local:
    image: mysql:5.6.34
    restart: always
    container_name: mysql.docker.local
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      default:
  redis.docker.local:
    container_name: redis.docker.local
    image: redis:3.2.10-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      default:

  # docker volume create portainer_data
  # docker run -d -p 81:9000 --name portainer --restart always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer
  portainer:
    image: portainer/portainer:latest
    container_name: "portainer"
    restart: always
    ports:
      - "81:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      default:

volumes:
  portainer_data:
  mysql_data:
  redis_data:

networks:
  default:
